version: '3'
services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: restaurantDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
    ports:
      - "5432:5432"
    restart: unless-stopped
  redis:
    image: redis
    environment:
      REDIS_PASSWORD: redis
    ports:
      - "6379:6379"
    restart: unless-stopped